language: node_js
node_js:
  - node
  - 10
cache: npm
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - npm run lint
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: 'node' # pre-installed version
      script:
        - npm install -g semantic-release@^15
        - npm run build
        - semantic-release
